server {
  listen 80;
  root /usr/share/nginx/html;

  location /_next/static/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
